# Generated by Django 5.1 on 2024-08-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movielist_app", "0002_streamplateform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="plateform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movielist",
                to="movielist_app.streamplateform",
            ),
            preserve_default=False,
        ),
    ]
